### ISSUE TITLE
Fix Typo and Gramatical errors in readme.md

### ISSUE THREAD

**Issue by ankitsagar** [ankitsagar/Smart-Agriculture#1]
SUMMARY
There are a lot of grammatical errors in readme.md. 

ISSUE TYPE
Documentation Report

COMPONENT NAME
readme.md

CONFIGURATION
N/A

OS / ENVIRONMENT
N/A

**Comment by Nawaid95** [comment]
Can I take this up?

**Comment by ankitsagar** [comment]
Sure go ahead.
